package.json
src/queryClient.ts
src/types.ts
src/ws/hooks.ts
src/ws/index.ts
src/ws/ws-client.ts
yarn.lock

PR to track progress on #9 
Possibility to setup Jest with more unit test, however would need to mock window WebSocket object (not available in NodeJS).
Related:
- #9 
- https://github.com/graasp/graasp-compose/pull/118
- https://github.com/graasp/graasp/pull/39

Add WebSocket client and React hooks for real-time content updates

---

src/config/constants.ts
src/queryClient.ts

This PR:
- sets the recommended default values for `staleTime` and `cacheTime`
- allows consumer clients to override these values at initialization of the exported `queryClient` factory through `QueryClientConfig`
- See #20 for more details

#20 Cache expiration time

---

src/hooks/item.ts
src/utils/item.ts

Fixes #143 in graasp-compose:
- https://github.com/graasp/graasp-compose/issues/143
Root cause of the crash was improper handling of undefined values for favorite ids. When a new user is created, the favorites extra is not defined. Thus multiple call sites did not have default safe values for undefined.
After merging this PR, the query-client version of graasp-compose MUST be updated

Fixes empty favorites crash for new users

---

babel.config.js
src/hooks/chat.ts
src/hooks/index.ts
src/hooks/item.ts
src/queryClient.ts
src/ws/hooks/chat.ts
src/ws/hooks/index.ts
src/ws/hooks/item.ts
src/ws/hooks/membership.ts
src/ws/index.ts
src/ws/ws-client.ts

This PR improves on #48 by integrating the websocket hooks into the API hooks directly, each with a boolean allowing consumer to enable websocket updates
Front-end applications that still use the previously `ws` exported member should update (Compose, Perform, ...).
Example:
```ts
// before
const item = useItem(itemId)
ws.hooks.useItemUpdates()
```
```ts
// should now be
const item = useItem(itemId)
// specific components can also optionally opt-out from receiving websocket updates:
const item = useItem(itemId, {getUpdates: false})
```

refactor: integrate ws hooks into api hooks

---

src/api/item.ts
src/mutations/item.ts

This trim the item's name when created or edited.
closes #52 , grasp-compose#153

fix: trim items names on add and edit

---

src/mutations/member.ts

This only update the user state when the backend confirms the logout
close #40

fix: remove cookie when logout is confirmed, prevents logout loop

---

src/api/routes.ts

close #108 
A simple bug fix to export the route `getItemsInCategories`

fix: export routes

---

src/api/routes.ts

Since now the search-plugin is registered as public, update corresponding route in hook

fix: change route url to public

---

package.json
src/api/axios.ts
src/api/itemTag.ts
src/api/routes.ts
src/config/keys.ts
src/hooks/item.test.ts
src/hooks/itemTag.test.ts
src/hooks/itemTag.ts
src/hooks/search.test.ts
src/mutations/item.test.ts
src/mutations/item.ts

This PR allows to use both private and public data for array response. This is needed because array response are always valid, even though the content is an error. This prevents to fallback on the public endpoint.
close #124

fix: fallback and merge private and public reponse for arrays

---

package.json
src/hooks/chat.ts
src/types.ts
src/utils/item.ts
yarn.lock

feat: add cryptoJS message id and itemChat hook typing

---

src/api/chat.ts
src/api/routes.ts
src/config/keys.ts
src/mutations/chat.test.ts
src/mutations/chat.ts
src/routines/chat.ts
src/ws/constants.ts
src/ws/hooks/chat.ts

This PR adds mutations to query client to access api endpoints to clear the chat.
closes #153

feat: add mutations to clear chat

---

.github/workflows/release-please.yml

This fixes an issue with how the composite workflow was called (it did not use the right name and the did not supply the arguments)
@dialexo sorry to double on this one ... 
closes #217

fix: npm publish composite

---

src/api/routes.ts

Bugfix: if an etherpad is created under a parent item, the `?` query prefix is missing. This PR uses the `addQueryPrefix` option to automatically enable this behaviour

fix: add query prefix on post etherpad

---

package.json
src/api/axios.ts
src/api/item.ts
src/hooks/item.test.ts
src/hooks/item.ts
src/hooks/itemTag.ts
src/mutations/authentication.test.ts
src/mutations/authentication.ts
src/mutations/membership.ts
test/wsUtils.tsx
yarn.lock

This fix is not the best solution, as we:
- do multiple calls for getting parents -> but it's the simplest way now to fallback on the public endpoint
- we ignore partial errors -> we might have a network error in the middle but it will be ignored
Both points are solved if we use a single and dedicated endpoint.
close #224

fix: get parents can return partial result

---

src/hooks/member.ts
src/hooks/mentions.ts

This PR fixes some issues with hook return types.
I had typed hooks because I had introduced a eslint rule that forced functions to have explicit return types. This is not considered a good practice, we should let TS infer the maximum it can. 
I revert these changes in this PR.

fix: remove wrong types of hooks

---

package.json
src/api/category.ts
src/api/chat.ts
src/hooks/item.ts
src/mutations/authentication.ts
src/mutations/chat.ts
src/utils/util.ts
yarn.lock

This PR:
- updates the repo name in `package.json` to match the github repo name
- updates the `variable` type for the `signOut` and `switchMember` useMutations functions
- changes the type of `isDataEqual` method to use a generic
closes #244

244 fix add currentmemberid back to signout mutation

---

src/hooks/member.test.ts
src/hooks/member.ts
test/constants.ts

This PR attempts to silently accept when getting an avatar fails with a 404.
There are a number of times when not being able to get an avatar is actually not an issue. Also a lot of users do not have avatars.
Other errors are re-thrown in order to be bubble them up as before.
closes #246

fix: catch avatar not found error

---

src/hooks/itemTag.ts

This PR fixes the return type of the `useTags` hook.
closes #253

fix(type): of useTags hook

---

.github/workflows/test.yml
package.json
src/types.ts
yarn.lock

This PR improves the type of the `notifier` to allow better support when used in typescript files.
The `type` key is set to be a string and the payload is an object with optional propoerties `error` and `payload`. Any string key with `unknown` value is also allowed to enable setting custom keys on the payload object.

fix: improve type of `notifier`

---

package.json
src/api/axios.ts
src/api/itemPublish.ts
src/hooks/itemPublish.ts
src/mutations/item.test.ts
src/mutations/item.ts
test/constants.ts

This PR fixes:
- GET collection's information for more than 15 ids
- Remove commented code
- Remove some invalidation due to some endpoints being async (copy, move, delete, recycle, restore many). Instead the `onMutation` callback will positively update the view, and websockets should do the job
close #277

fix: split get many publish info, no settled for many calls

---

src/api/item.ts
src/config/keys.ts
src/hooks/action.ts
src/hooks/item.test.ts
src/hooks/item.ts
src/ws/hooks/item.test.ts

This PR improves `useParents` type. It mainly allows `path` to be optional.
Tests are also fixed and enabled back.
It also includes a change for an optional id for `useActions`

refactor: update useParents types, enable back tests

---

src/api/routes.ts

Related to https://github.com/graasp/graasp/pull/427. 
We decided to fix the bug in the queryClient to stay consistent with the fact that all queryParams are singular when they are an array.

fix: use `categoryId` instead of `categoryIds`

---

src/api/item.ts

This PR fixes a bug where the result data was not extracted from the axios response in etherpad queries

fix: extract etherpad object from api response

---

package.json
src/api/routes.ts
yarn.lock

This PR exposes the `buildGetAllPublishedItems` builder function on the `API_ROUTE` named export. 
This public export will be used to configure route intercepts in cypress for example.

fix: export public getAllPublishedItems route

---

src/api/authentication.ts
src/api/routes.ts
src/mutations/authentication.test.ts
src/mutations/authentication.ts

This PR adds:
- hooks to register using the mobile endpoints
- tests for the mobile signin and register endpoints

feat: add mobile sign up hooks

---

src/queryClient.ts

We should remove this hidden dependency on `process.env` as this is for example not defined when using vite.

fix: remove default dependency on `process.env` for configuration

---

src/mutations/authentication.test.ts
src/mutations/authentication.ts

Ref https://github.com/graasp/graasp-auth/pull/183
After some discussion, this PR only fixes a bug in the test. 
The notifier should get the Graasp error message from the `error.response.data.message` to be able to translate them.

fix: use more explicit error message when signinwithpassword without a password set

---

src/api/apps.ts

This PR handles back the app-id we used to use for apps. 
This allows twente apps to work again eg https://player.graasp.org/62915d32-ba68-476c-8602-5b4f6f21c32c
fix #416

fix: use app id if key does not exist for requestApiAccessToken

---

src/api/search.ts
src/config/keys.ts
src/hooks/search.test.ts
src/hooks/search.ts

This PR changes the pagination mechanism to use the `limit` and `offset` strategies instead of the `page` and `histPerPage` strategy.
If `page` is set, then `limit` and `offset` are computed from `page` and `elementsPerPage` as such:
`limit = elementsPerPage`
`offset = elementsPerPage * (page - 1)` since page is 1-indexed
If `page` is not set, then `limit` and `offset` are used as is (falling back to default values if undefined).

fix: use limit and offset

---

package.json
src/api/action.ts
src/api/apps.ts
src/api/authentication.ts
src/api/category.ts
src/api/chat.ts
src/api/invitation.ts
src/api/item.ts
src/api/itemExport.ts
src/api/itemFavorite.ts
src/api/itemFlag.ts
src/api/itemLike.ts
src/api/itemLogin.ts
src/api/itemPublish.ts
src/api/itemTag.ts
src/api/itemValidation.ts
src/api/member.ts
src/api/membership.ts
src/api/mentions.ts
src/api/search.test.ts
src/api/search.ts
src/api/subscription.ts
src/queryClient.ts
src/types.ts
test/utils.tsx
test/wsUtils.tsx

I've refactored the api files to use the same axios instance. 
Eventually this will help define interceptors externally (like needed for mobile)
close #489

refactor: use common axios instance

---

src/api/action.ts
src/api/routes.ts
src/config/keys.ts
src/hooks/action.test.ts
src/hooks/action.ts
src/utils/action.ts
test/constants.ts
yarn.lock

This PR fixes incorrect types in the hooks.
The API returns the `createdAtDay` as a ISOString representation of a date. 
We have an interceptor for axios that automatically applies a transform to convert dates formatted in strings to `Date` objects. So the correct type that the consumer will see in this case is `Date`.

fix(type): use correct type for transformed date

---

src/utils/action.ts

In this PR I update the type of the `useAggregateAction` to support using string literals instead of named `Context` enum only (it is still possible to use `Context` enum but not mandatory.
This allows us to use a subset of `Context` in analytics for example. See the linked PR: https://github.com/graasp/graasp-analytics/pull/264

fix: allow union litterals in aggregate

---

package.json
src/api/index.ts
src/api/item.ts
src/api/itemGeolocation.ts
src/api/routes.ts
src/config/errors.ts
src/config/keys.ts
src/hooks/index.ts
src/hooks/itemGeolocation.test.ts
src/hooks/itemGeolocation.ts
src/mutations/index.ts
src/mutations/item.test.ts
src/mutations/item.ts
src/mutations/itemGeolocation.test.ts
src/mutations/itemGeolocation.ts
src/routines/index.ts
src/routines/itemGeolocation.ts
test/constants.ts
yarn.lock

feat: add geolocation hooks and mutations

---

src/config/constants.ts
src/hooks/apps.ts
src/hooks/category.ts
src/hooks/item.ts
src/hooks/member.ts
src/mutations/item.ts

Reading the docs more carefully, there was a miss-understanding in the use of `staleTime` and `cacheTime`.
So for our application we want:
- a `staleTime` that represents our usual loading time, or until all components have rendered on screen and we would like to minimise the number of duplicated request to the backend. Ideally only one per resource.
- a `cacheTime` that is big enough so that when navigating between pages we can display the "old" data before updating it -> this will remove a lot of loading spinners once we have data (even if it is slightly older).
Proposed default values:
- `staleTime`: 3 seconds
- `cacheTime`: 5 minutes (this is the default for react query)
Understanding this difference we should change `Constant cache time` to actually be a `Constant stale time` for …

fix: better understanding of `staleTime` and `cacheTime` 

---

src/api/routes.ts
src/hooks/item.test.ts

This PR refers to (graasp/graasp#787):
- Allow to filter the accessible items by an array of types.
- Another PR (#606) is created to do the same with the children.
- The backend already support that in graasp/graasp#787.
- It is in another PR, because we have to update the UI to use new version of `useChildren`.

feat: add types filter in useAccessible

---

package.json
yarn.lock

This change allows to remove the duplication of `@graasp/sdk` between query-client node-modules and the version that will be used in builder for example. 
In practice this means a reduction from **12MB** to **9MB** with this PR alone when used in builder. (yes sdk is faaat, this will be fixed in a next PR)

fix: make graasp deps peer

---

src/ws/hooks/item.ts

Invalidates the item's content and published information to refetch data when validation is done. Its allow to automatically show the published status on the frontend.

feat: invalidate publishedInfo on validate feedback

---

src/api/item.test.ts
src/api/item.ts
src/config/keys.ts
src/hooks/item.test.ts
src/hooks/item.ts

fix: add params to getDescendants

---

src/routes.ts

Fix issue [graasp/graasp#1394](https://github.com/graasp/graasp-builder/issues/1394#issue-2444370965)

fix(params): use parentId in search params of import zip and h5p

---

src/api/membership.ts
src/mutations/membership.test.ts
src/mutations/membership.ts

The post item membership is used only when upgrading a membership in a child. 
So I also took the opportunity to remove the email search and directly provide the member id since we always have it. If not, we can use `shareItem` does deal for us with the email.
fix #902

fix: fix post item membership

---

src/api/itemExport.test.ts
src/api/itemExport.ts

This has been tested in builder and works as expected with filename containing emojis for example.
fix #918

fix: decode exported filename
