src/config/keys.ts, src/hooks/member.ts, yarn.lock
=> Add GET member by id

src/api/item.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/item.ts, src/utils/item.ts
=> Add GET items by ids

src/api/membership.ts, src/api/routes.ts, src/config/keys.ts, src/mutations/index.ts, src/mutations/membership.ts, src/routines/membership.ts
=> feat: add PATCH and DELETE item membership mutations

src/hooks/item.ts
=> Get single item in useItems when only one id is given

src/api/index.ts, src/api/itemFlag.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/index.ts, src/hooks/itemFlag.ts, src/mutations/index.ts, src/mutations/itemFlag.ts, src/routines/index.ts, src/routines/itemFlag.ts
=> Add item flagging functionality

src/queryClient.ts, src/types.ts, yarn.lock
=> feat: add keepPreviousData to config

src/api/item.ts, src/api/member.ts, src/api/routes.ts, src/mutations/item.ts, src/types.ts
=> feat: add public items endpoints

src/api/item.ts, src/api/routes.ts, src/hooks/item.ts
=> Get ordered children by default

package.json, src/config/constants.ts, src/mutations/member.ts, yarn.lock
=> refactor: remove cookie from browser when signing out

.eslintrc, .github/workflows/coverage.yml, .husky/pre-push, babel.config.js, jest.config.ts, package.json, src/api/member.ts, src/api/routes.ts, src/api/utils.ts, src/config/constants.ts, src/config/keys.ts, src/hooks/item.test.ts, src/hooks/item.ts, src/hooks/member.test.ts, src/hooks/member.ts, src/mutations/member.test.ts, src/mutations/member.ts, src/types.ts, test/constants.ts, test/setupTests.ts, test/utils.tsx, yarn.lock
=> test: set up first test and dependencies

src/hooks/item.ts
Closes #54 
See https://github.com/graasp/graasp-perform/issues/13#issuecomment-894311797
=> fix: disable ws updates for useChildren if enabled option set to false

.yarnrc.yml, src/api/routes.ts
=> refactor: add checksumBehavior in yarnrc, add routes to API_ROUTES

src/api/routes.ts
=> fix: ensures the email is always sent in lowercase

src/api/routes.ts
Updates query-client for [graasp#73](https://github.com/graasp/graasp/issues/73)
close #61
=> Update GetMemberBy Route

package.json, src/api/member.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/index.ts, src/hooks/member.test.ts, src/hooks/member.ts, test/constants.ts
=> feat: add hook for getting multiple members by id

src/api/item.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/item.test.ts, src/hooks/item.ts, src/mutations/item.test.ts, src/mutations/item.ts, src/routines/item.ts, src/types.ts, test/constants.ts, test/utils.tsx
close #66
depends on https://github.com/graasp/graasp/pull/79
=> feat: add recycle bin endpoints

src/config/keys.ts, src/hooks/itemTag.test.ts, src/hooks/itemTag.ts, src/mutations/chat.test.ts, src/mutations/chat.ts, src/mutations/index.ts, src/mutations/item.test.ts, src/mutations/item.ts, src/mutations/itemFlag.test.ts, src/mutations/itemFlag.ts, src/mutations/itemLogin.test.ts, src/mutations/itemLogin.ts, src/mutations/itemTag.test.ts, src/mutations/itemTag.ts, src/mutations/membership.test.ts, src/mutations/membership.ts, src/routines/chat.ts, src/routines/index.ts, src/types.ts, src/ws/constants.ts, src/ws/hooks/chat.test.ts, src/ws/hooks/chat.ts, src/ws/hooks/item.test.ts, src/ws/hooks/item.ts, src/ws/hooks/membership.test.ts, src/ws/hooks/membership.ts, test/constants.ts, test/setupTests.ts, test/utils.tsx, test/wsUtils.tsx
=> test: add ws hook tests and more missing tests

src/api/item.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/item.test.ts, src/hooks/item.ts, src/mutations/item.test.ts, src/mutations/item.ts, src/routines/item.ts, src/utils/item.ts
=> feat: add restore mutation, update delete mutations

src/config/keys.ts, src/hooks/item.test.ts, src/hooks/item.ts, src/mutations/item.test.ts, src/queryClient.ts, src/types.ts
=> feat: allow to get children of multiple items

src/utils/item.ts
=> fix: do not order original array on hash

src/api/axios.ts, src/api/category.ts, src/api/routes.ts, src/api/utils.ts, src/hooks/category.test.ts
=> refactor: update public categories routes

src/api/routes.ts, src/routines/item.ts
=> feat: add import zip endpoint

src/api/category.ts, src/api/routes.ts, src/hooks/category.test.ts
=> fix: fix function name

src/api/itemLogin.ts
=> fix: do not check authentication for GET item login

.husky/commit-msg, package.json, src/api/itemLogin.ts
=> fix: do not check user authentication on post item login

src/api/itemTag.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/index.ts, src/hooks/itemTag.test.ts, src/hooks/itemTag.ts
=> feat: add hooks to get tags for multiple items

package.json
This PR adds types declaration to use with TypeScript.
closes #133
=> 133/add types to package.json

src/api/chat.ts, src/api/routes.ts, src/config/keys.ts, src/mutations/chat.ts, src/routines/chat.ts, src/types.ts, src/ws/hooks/chat.ts
=> feat: add websocket for delete message operation

src/api/chat.ts, src/api/routes.ts, src/config/keys.ts, src/mutations/chat.test.ts, src/mutations/chat.ts, src/routines/chat.ts, src/ws/hooks/chat.test.ts, src/ws/hooks/chat.ts, test/constants.ts
=> feat: add message editing and mutations

package.json, src/api/apps.ts, src/api/category.ts, src/api/member.ts, src/hooks/apps.ts, src/hooks/category.ts, src/hooks/item.ts, src/queryClient.ts, src/types.ts, src/utils/util.ts, tsconfig.json
Some types are added to be used/infered in builder.
close #205
=> 205 typescript

src/types.ts
This PR makes some properties of the default config optional-
closes #210
=> fix: make defaultConfig properties optional

package.json, src/api/item.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/item.ts, src/mutations/item.ts, src/routines/item.ts, src/types.ts, yarn.lock
Implement queries to access etherpad back-end
=> feat: add etherpad queries

src/types.ts, test/constants.ts
=> fix: fix item tag and item category types

src/api/action.ts, src/hooks/action.ts, src/mutations/authentication.test.ts, src/mutations/authentication.ts, src/mutations/membership.ts, src/types.ts, test/constants.ts
=> fix: complete action type

src/api/apps.ts, src/api/itemLogin.ts, src/mutations/itemLogin.ts
This PR allows optional properties in postItemLogin.
closes #249
=> fix: allow optional properties

package.json, src/config/constants.ts, src/hooks/item.test.ts, src/hooks/member.test.ts, src/mutations/item.test.ts, src/mutations/item.ts, src/mutations/member.test.ts, src/mutations/member.ts, tsconfig.test.json, yarn.lock
This PR uses ThumbnailSizes defined in sdk instead of own constant
closes #251
=> fix: use ThumbnailSize from sdk

src/api/search.ts, src/hooks/search.ts, src/mutations/itemFavorite.ts, src/mutations/itemLike.test.ts, src/mutations/itemLike.ts, test/constants.ts, yarn.lock
- fix: update name of parameter for useDeleteItemLike mutation
- fix: change default mutations to custom hooks
- fix(test): correct tests to be compliant with the api
it looks like the member is not returned in the mutation, we should address that and correct the type in sdk. This also means we need to supply the `memberId` to the mutation like before.
=> fix: argument in useDeleteItemLike and refactor to use custom mutation hook

renovate.json
=> build: setup renovate

src/ws/mock-ws-client.ts
This PR fixes a small bug that only appears in the player cypress tests.
=> fix: action may be undefined

src/api/axios.ts
=> refactor: concat only if error exists

.github/workflows/test.yml, src/api/authentication.ts, src/api/axios.ts, src/api/routes.ts, src/mutations/authentication.ts, src/mutations/invitation.ts, src/mutations/item.test.ts, src/mutations/item.ts, src/mutations/itemTag.ts, src/mutations/member.ts, src/mutations/membership.test.ts, src/mutations/membership.ts, src/types.ts, src/ws/hooks/item.ts, test/constants.ts, test/utils.tsx, tsconfig.test.json
=> feat: add mobile auth queries

src/api/itemPublish.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/itemPublish.ts
=> feat: add most liked and most recent collections 

src/mutations/item.test.ts, src/mutations/item.ts
=> fix: invalidate children key on reorder

.gitignore, package.json, src/api/action.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/action.test.ts, src/hooks/action.ts, src/utils/action.ts, test/constants.ts, yarn.lock
=> feat: add aggregate actions

src/hooks/itemTag.test.ts, src/hooks/itemTag.ts
=> refactor: split get item tags

src/api/authentication.ts, src/mutations/authentication.ts
=> feat: expose url parameter for auth redirection

package.json, src/api/routes.ts, src/api/search.test.ts, src/api/search.ts, src/config/keys.ts, src/hooks/search.test.ts, src/hooks/search.ts, src/hooks/useDebounce.ts, src/types.ts, yarn.lock
Update the search hook to handle some meilisearch parameters.
=> 421 meilisearch

package.json, src/api/member.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/member.test.ts, src/hooks/member.ts, yarn.lock
I forgot to merge this one for account D: 
close #414
=> feat: add get member storage hook

src/api/action.ts, src/api/routes.ts, src/mutations/action.test.ts, src/mutations/action.ts, src/routines/action.ts
=> feat: add post item action mutation

src/api/item.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/item.test.ts, src/hooks/item.ts, src/mutations/item.ts, src/routines/item.ts, src/types.ts, src/ws/constants.ts, src/ws/hooks/item.test.ts, src/ws/hooks/item.ts
=> feat: add accessible items endpoint

src/api/routes.ts
=> fix: update sort params for accessible items

package.json, src/hooks/action.test.ts, src/hooks/chat.test.ts, src/hooks/invitation.test.ts, src/hooks/item.test.ts, src/hooks/itemLike.test.ts, src/hooks/itemTag.test.ts, src/hooks/member.test.ts, src/hooks/membership.test.ts, src/hooks/mention.test.ts, src/mutations/action.test.ts, src/mutations/chat.test.ts, src/mutations/invitation.test.ts, src/mutations/item.test.ts, src/mutations/itemFlag.test.ts, src/mutations/itemLike.test.ts, src/mutations/itemLogin.test.ts, src/mutations/itemPublish.test.ts, src/mutations/itemTag.test.ts, src/mutations/member.test.ts, src/mutations/membership.test.ts, src/mutations/mention.test.ts, src/mutations/publicProfile.test.ts, src/ws/hooks/chat.test.ts, src/ws/hooks/item.test.ts, src/ws/hooks/membership.test.ts, src/ws/hooks/mentions.test.ts, test/constants.ts, yarn.lock
Use sdk's factories to replace global constants in tests.
=> test: use item and member factories in tests

package.json, src/api/itemGeolocation.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/itemGeolocation.test.ts, src/hooks/itemGeolocation.ts, src/mutations/itemGeolocation.test.ts, src/mutations/itemGeolocation.ts, src/routines/itemGeolocation.ts, test/constants.ts, yarn.lock
- allow returning null geolocation
- new hook: useAddressFromCoordinates
- add parentItemId for search hook
- add addressLabel on put
=> feat: add geolocation address and parent item

src/api/itemPublish.ts
Adapting the return type from following the change in behaviour from https://github.com/graasp/graasp/pull/819
=> fix: adapt return type of item publish info

package.json, src/api/item.ts, yarn.lock
- Allow to add an item with a given `descriptionPlacement` setting.
- See graasp/graasp-ui#694 for more informations.
=> feat: add descriptionPlacement in postItem

src/api/index.ts, src/api/itemBookmark.ts, src/api/routes.ts, src/config/keys.ts, src/hooks/index.ts, src/hooks/itemBookmark.ts, src/hooks/itemFavorite.test.ts, src/mutations/index.ts, src/mutations/itemBookmark.test.ts, src/mutations/itemBookmark.ts, src/routines/index.ts, src/routines/itemBookmark.ts, src/routines/itemFavorite.ts, test/constants.ts
=> feat!: rename favorite to bookmark

package.json, src/api/item.ts, src/mutations/item.test.ts, src/mutations/item.ts, yarn.lock
Need graasp/graasp-sdk#454 be merged firstly.
=> feat: add displayName to postItem payload

src/api/member.ts, src/mutations/member.test.ts, src/mutations/member.ts
=> fix: trim member name before posting to API

src/api/item.ts, src/api/routes.ts, src/mutations/item.test.ts, src/mutations/item.ts
In this PR:
- Add endpoint postItemWithThumbnail to take FormData
=> feat: add postItem hook with thumbnail

src/api/axios.test.ts, src/api/axios.ts
=> fix: add tests and ensure we do not send a request when array is empty

.github/workflows/release-please.yml, .gitignore
- **fix: update release-please workflow**
- **fix: add conditional checkout**
=> chore: update release please workflow

src/member/api.ts, src/member/mutations.ts, src/member/routes.ts, src/member/routines.ts
Linked to https://github.com/graasp/graasp/pull/1158
=> fix: do not call logout on delete member as the backend does it automatically

src/item/thumbnail/hooks.test.ts, src/item/thumbnail/hooks.ts
Allow to pass the full item to fetch "hasThumbnail" in the settings for `useThumbnailUrl`
=> feat: check hasThumbnail on item for thumbnail

package.json, src/item/accessible/api.ts, src/item/accessible/hooks.test.ts, src/item/accessible/hooks.ts, src/item/routes.ts, src/keys.ts, src/types.ts, yarn.lock
In this PR I use the new sdk version with the lifted pagination types.
=> fix: update pagination

src/keys.ts, src/member/api.ts, src/member/fixtures.ts, src/member/hooks.test.ts, src/member/hooks.ts, src/member/routes.ts
=> feat: add new hook useMemberStorageFiles

src/item/accessible/hooks.test.ts, src/item/accessible/hooks.ts, src/item/hooks.test.ts, src/item/hooks.ts, src/item/routes.ts, src/item/types.ts, src/keys.ts
Add keywords to children and accessible calls.
=> feat: add keywords got children and accessible

src/member/api.ts, src/member/mutations.test.ts, src/member/mutations.ts, src/member/routes.ts
In this PR:
- add password creation route
- update password edit route
changes are linked to the backend PR https://github.com/graasp/graasp/pull/1236
=> fix: add member password routes

src/api/invitation.ts, src/mutations/membership.test.ts, src/mutations/membership.ts
Move all logic in the backend.
=> feat: move share item logic in backend

src/member/api.ts, src/member/mutations.test.ts, src/member/mutations.ts, src/member/routes.ts, src/member/routines.ts, src/routines/member.ts
=> feat: add member export data mutation

src/member/api.ts, src/member/mutations.test.ts, src/member/mutations.ts, src/member/routes.ts
In this PR:
- remove deprecated hook
- update tests to target new hook instead
=> fix: update to remove delete member hook as it is deprecated

package.json, src/api/authentication.ts, src/member/mutations.test.ts, src/mutations/authentication.test.ts, src/mutations/authentication.ts, src/routes.ts, src/routines/authentication.ts, yarn.lock
=> feat: password reset request mutations

package.json, src/api/itemLogin.ts, src/keys.ts, src/mutations/itemLogin.test.ts, src/mutations/itemLogin.ts, src/routes.ts, src/routines/itemLogin.ts, test/constants.ts, yarn.lock
=> feat: remove delete item login schema, update state

src/member/api.ts, src/member/mutations.test.ts, src/member/mutations.ts, src/member/routes.ts
In this PR:
- deprecate updating any member
=> fix: deprecate updating any member

src/hooks/index.ts, src/item/accessible/hooks.test.ts, src/item/accessible/hooks.ts, src/item/api.ts, src/item/hooks.ts, src/item/mutations.test.ts, src/item/mutations.ts, src/item/recycled/api.ts, src/item/recycled/hooks.test.ts, src/item/recycled/hooks.ts, src/item/recycled/routes.ts, src/item/routes.ts, src/keys.ts, src/ws/hooks/item.test.ts, src/ws/hooks/item.ts
=> feat: add pagination to recycled

package.json, src/api/search.ts, src/hooks/search.test.ts, src/hooks/search.ts, src/keys.ts, yarn.lock
=> feat: add langs in search hook

src/item/recycled/api.ts, src/item/recycled/hooks.test.ts, src/item/recycled/hooks.ts, src/item/recycled/routes.ts
Get items directly instead of recycled item data.
=> feat: get items for get own recycled items

src/member/api.ts, src/member/hooks.test.ts, src/member/hooks.ts, src/member/routes.ts, src/mutations/membership.test.ts
Remove get many members by id, also some remaining data about getting members by email.
=> refactor: remove unused get many members
